# car-sim — unified backend. Serves the section pages; the real-map simulator (/drive)
# is a client-side canvas app that streams baked map tiles served as static JSON.
# MVP: one Prague district (Vinohrady). No DB.

import hashlib
import json
import os
import re
import secrets
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware
from starlette.responses import Response

from . import auth, db, docs_laws, ui

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent
CITIES = Path(os.environ.get("CITIES_DIR", ROOT / "data" / "cities"))
DOCS = Path(os.environ.get("DOCS_DIR", ROOT / "data" / "docs"))
STATIC = BASE / "static"
# admin-uploaded custom object icons (msg 2983 ph3). Lives next to the SQLite DB so it shares the
# persistent named volume (the image's data/ is rebuilt each deploy; uploads must NOT live there).
UPLOADS = Path(os.environ.get("CARSIM_UPLOADS", db.DB_PATH.parent / "uploads"))


def _build_token(root: Path) -> str:
    """Short hash of the static tree's newest mtime. Changes only when an asset
    changes, so the versioned path /s/<token>/ stays stable across no-op restarts
    and rolls forward on a real deploy."""
    newest = 0.0
    for p in root.rglob("*"):
        if p.is_file():
            newest = max(newest, p.stat().st_mtime)
    return hashlib.sha1(str(newest).encode()).hexdigest()[:10]


BUILD = _build_token(STATIC)


class ImmutableStatic(StaticFiles):
    """Versioned assets are content-addressed by the /s/<BUILD>/ path prefix, so they
    can be cached forever — a new deploy serves new URLs for the whole nested
    ES-module graph (a query string can't reach nested imports; a path prefix does)."""

    def file_response(self, *args, **kwargs) -> Response:
        resp = super().file_response(*args, **kwargs)
        resp.headers["Cache-Control"] = "public, max-age=31536000, immutable"
        return resp


class RevalidatingStatic(StaticFiles):
    """`Cache-Control: no-cache` → browser/CDN revalidate via ETag (cheap 304 when
    unchanged). Used for data tiles, which aren't path-versioned."""

    def file_response(self, *args, **kwargs) -> Response:
        resp = super().file_response(*args, **kwargs)
        resp.headers["Cache-Control"] = "no-cache"
        return resp


class IconStatic(RevalidatingStatic):
    """Admin-uploaded custom icons (msg 2983 ph3). Defence-in-depth for the SVG case: a strict CSP
    (`script-src 'none'`) neutralises any script an uploaded SVG might carry if opened directly, and
    `nosniff` stops MIME confusion. They still render fine via <img>/canvas drawImage."""

    def file_response(self, *args, **kwargs) -> Response:
        resp = super().file_response(*args, **kwargs)
        resp.headers["Content-Security-Policy"] = "default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; sandbox"
        resp.headers["X-Content-Type-Options"] = "nosniff"
        return resp


# Disable FastAPI's auto Swagger/ReDoc — this is a user-facing app, and the built-in /docs would otherwise
# shadow our Official-documents page (msg 2802c).
app = FastAPI(title="car-sim", docs_url=None, redoc_url=None, openapi_url=None)

# signed-cookie sessions for auth. SECRET_KEY must be stable across restarts (set in compose) or sessions
# drop on every deploy; a random fallback keeps dev working. same_site=lax so the OAuth redirect keeps the
# cookie; Secure flag on unless explicitly disabled for plain-http local runs.
SECRET_KEY = os.environ.get("SECRET_KEY") or secrets.token_hex(32)
SESSION_HTTPS = os.environ.get("SESSION_HTTPS", "1") != "0"
app.add_middleware(SessionMiddleware, secret_key=SECRET_KEY, same_site="lax",
                   https_only=SESSION_HTTPS, max_age=60 * 60 * 24 * 30)

templates = Jinja2Templates(directory=str(BASE / "templates"))
templates.env.cache = None  # avoid a Jinja LRUCache key issue under Python 3.14 (prod uses 3.12)
templates.env.globals["asset_base"] = f"/s/{BUILD}"  # versioned static prefix for all templates
templates.env.globals["hdr"] = ui                     # shared common header (msg 2837)
ui.ASSET_VER = BUILD                                  # version the favicon link so it busts on icon change
auth.templates = templates                            # share the configured templates with the auth router
app.include_router(auth.router)

# localized intro strings (msg 2837), generated by tools (Gemini) into data/i18n/intro.json
try:
    _INTRO_I18N = json.loads((ROOT / "data" / "i18n" / "intro.json").read_text(encoding="utf-8"))
except (OSError, ValueError):
    _INTRO_I18N = {}


def intro_strings(lang: str) -> dict:
    return _INTRO_I18N.get(lang) or _INTRO_I18N.get("en") or {}


# localized UI chrome for the app sections lives in ui.py (shared with auth.py) — msg 3080/3081/3083
app_strings = ui.app_strings


@app.on_event("startup")
def _startup():
    db.init_db()
    auth.seed_admin()   # out-of-band admin bootstrap from SEED_ADMIN_EMAIL/PASSWORD env (if set)


app.mount(f"/s/{BUILD}", ImmutableStatic(directory=str(STATIC)), name="assets")
app.mount("/static", RevalidatingStatic(directory=str(STATIC)), name="static")  # legacy/direct hits
if CITIES.exists():
    app.mount("/citydata", RevalidatingStatic(directory=str(CITIES)), name="citydata")
UPLOADS.mkdir(parents=True, exist_ok=True)
app.mount("/uploads", IconStatic(directory=str(UPLOADS)), name="uploads")  # admin custom icons (ph3)

# quizzes — migrated from the standalone "ulice" apps (msg 2802), each mounted as a sub-app under /quiz
from .quiz.photo import photo_app          # noqa: E402  (after app/mounts so import side-effects are last)
from .quiz.situations import sim_app       # noqa: E402
app.mount("/quiz/photo", photo_app)
app.mount("/quiz/situations", sim_app)

# Cities offered on the homepage selector + /drive?city=. Each city's whole-city bake lives at
# data/cities/<cc>/<slug>/<district>/ (one bake per city = the whole city). CZ traffic rules
# (countries/cz.yaml) apply nationwide, so every CZ city reuses the same profile. To add a city:
# bake it (tools/bake_city_pbf.py) then add one line here (Vlad msg 2931, by population).
CITY_REGISTRY = [
    {"cc": "cz", "slug": "praha",   "name": "Praha",   "district": "prague"},
    {"cc": "cz", "slug": "brno",    "name": "Brno",    "district": "brno"},
    {"cc": "cz", "slug": "ostrava", "name": "Ostrava", "district": "ostrava"},
    {"cc": "cz", "slug": "plzen",   "name": "Plzeň",   "district": "plzen"},
]
DEFAULT_CITY_SLUG = "praha"
_SLUG_RE = re.compile(r"[a-z0-9_-]{1,40}")


def _resolve_dir(cc: str, city: str, district: str) -> Path | None:
    """Baked-district directory under data/cities/<cc>/<city>/, refusing path traversal. Returns the
    dir only if cc/city/district are safe slugs, the path stays inside the city dir, and the district
    is actually baked (has meta.json). Otherwise None."""
    if not all(_SLUG_RE.fullmatch(s or "") for s in (cc, city, district)):
        return None
    base = (CITIES / cc / city).resolve()
    d = (base / district).resolve()
    if d.parent != base or not (d / "meta.json").is_file():
        return None
    return d


def _city(slug: str) -> dict | None:
    """Registry entry for a city slug IF its whole-city bake exists on disk, else None."""
    for c in CITY_REGISTRY:
        if c["slug"] == slug and _resolve_dir(c["cc"], c["slug"], c["district"]):
            return c
    return None


def _available_cities() -> list[dict]:
    """Registry cities whose bake is present — drives the homepage city selector."""
    return [c for c in CITY_REGISTRY if _resolve_dir(c["cc"], c["slug"], c["district"])]


# Standard object-icon library (msg 2983 ph3) — kind → emoji pictogram, mirrors ICON_GLYPH in
# render/draw.js. The admin picks one of these, or uploads a custom image instead. Order = picker order.
STD_ICONS: dict[str, str] = {
    "station": "🚉", "bus_station": "🚌", "airport": "✈️", "square": "⛲", "castle": "🏰",
    "museum": "🏛️", "monument": "🗿", "attraction": "⭐", "theatre": "🎭", "church": "⛪",
    "university": "🎓", "hospital": "🏥", "stadium": "🏟️", "townhall": "🏛️",
    "pharmacy": "💊", "atm": "🏧", "bank": "🏦", "food": "🍽️", "fuel": "⛽",
    "police": "🚓", "fire": "🚒", "post": "✉️", "shop": "🛒",
}


def _city_proj(slug: str) -> dict | None:
    """The {lat0,lon0,kx,ky} local-metres projection a city was baked with (from its meta.json),
    so admin-entered lat/lon can be projected to the same world coords the map labels/edges use."""
    c = _city(slug)
    d = _resolve_dir(c["cc"], c["slug"], c["district"]) if c else None
    if d is None:
        return None
    try:
        return json.loads((d / "meta.json").read_text(encoding="utf-8")).get("proj")
    except (OSError, ValueError):
        return None


def _project(proj: dict, lat: float, lon: float) -> tuple[float, float]:
    """lat/lon → world metres, identical to tools/bake_city.make_proj (y north-positive)."""
    return ((lon - proj["lon0"]) * proj["kx"], (lat - proj["lat0"]) * proj["ky"])


@app.get("/healthz")
def healthz():
    return {"ok": True, "cities": [c["slug"] for c in _available_cities()]}


@app.get("/favicon.svg", include_in_schema=False)
@app.get("/favicon.ico", include_in_schema=False)
def favicon():
    # 🚗 car mark (also the header logo). Served at the well-known paths so every page gets it.
    return FileResponse(STATIC / "favicon.svg", media_type="image/svg+xml",
                        headers={"Cache-Control": "public, max-age=86400"})


@app.get("/route")
def route(city: str = DEFAULT_CITY_SLUG, district: str = "prague",
          fx: float = 0, fy: float = 0, tx: float = 0, ty: float = 0):
    """Shortest drivable path (one-ways honoured) between two map points, as a polyline."""
    from .routing import get_router
    c = _city(city)
    d = _resolve_dir(c["cc"], c["slug"], district) if c else None
    if d is None:
        return JSONResponse({"polyline": [], "length_m": 0, "error": "unknown city/district"}, status_code=404)
    r = get_router(d / "graph.json")
    if r is None:
        return JSONResponse({"polyline": [], "length_m": 0, "error": "no graph"}, status_code=404)
    res = r.route(fx, fy, tx, ty)
    return JSONResponse(res or {"polyline": [], "length_m": 0})


HTML_HEADERS = {"Cache-Control": "no-cache"}  # never cache the HTML that names the asset build token


@app.get("/", response_class=HTMLResponse)
def intro(request: Request):
    lang = ui.resolve_lang(request)
    return templates.TemplateResponse(request, "intro.html", {
        "lang": lang, "t": intro_strings(lang), "cities": _available_cities(),
        "user": auth.current_user(request),
    }, headers=HTML_HEADERS)


@app.get("/quiz", response_class=HTMLResponse)
def quiz_hub(request: Request):
    """Quizzes hub — indexes the sub-quizzes (photo quiz live; situations/signs/rules soon)."""
    lang = ui.resolve_lang(request)
    return templates.TemplateResponse(request, "quiz.html", {
        "lang": lang, "t": app_strings(lang), "user": auth.current_user(request),
    }, headers=HTML_HEADERS)


@app.get("/docs", response_class=HTMLResponse)
def docs(request: Request, q: str = ""):
    """Official documents — the FULL texts of the Czech transport laws (road/rail/air/water, from the
    legalize-cz source), with diacritics-insensitive full-text search across every § (msg 2820).
    Law titles/cards localize to any UI language that has machine translations (msg 2828)."""
    lang = ui.resolve_lang(request)
    langs = docs_laws.hub_langs()
    if lang not in {c for c, _ in langs}:
        lang = "cs"
    query = (q or "").strip()
    results = docs_laws.search(query) if query else None
    return templates.TemplateResponse(request, "docs.html", {
        "lang": lang, "q": query, "results": results,
        "groups": docs_laws.laws_by_mode(lang), "ui": docs_laws.ui(lang), "langs": langs,
        "user": auth.current_user(request),
    }, headers=HTML_HEADERS)


@app.get("/docs/{law_id}", response_class=HTMLResponse)
def docs_law(request: Request, law_id: str):
    """Full text of one law, §-by-§, in the chosen language (machine-translated for non-Czech, msg 2828),
    with an in-page filter and a link to the authoritative e-Sbírka."""
    law = docs_laws.LAW_BY_ID.get(law_id)
    if law is None:
        raise HTTPException(status_code=404, detail="unknown law")
    lang = ui.resolve_lang(request)
    langs = docs_laws.law_langs(law_id)
    if lang not in {c for c, _ in langs}:
        lang = "cs"
    localized = docs_laws.localize_law(law, lang)
    return templates.TemplateResponse(request, "docs_law.html", {
        "lang": lang, "law": localized, "ui": docs_laws.ui(lang), "langs": langs,
        "translated": localized["translated"], "user": auth.current_user(request),
    }, headers=HTML_HEADERS)


@app.get("/drive", response_class=HTMLResponse)
def drive(request: Request, city: str = DEFAULT_CITY_SLUG):
    # unknown/un-baked slug → fall back to the default city, then to the first registry entry so `c`
    # is always a dict (a missing default bake degrades to an empty map, never a 500).
    c = _city(city) or _city(DEFAULT_CITY_SLUG) or CITY_REGISTRY[0]
    cc, city_slug, district = c["cc"], c["slug"], c["district"]
    d = _resolve_dir(cc, city_slug, district)
    snapshot = None
    if d is not None:
        try:
            snapshot = json.loads((d / "meta.json").read_text(encoding="utf-8")).get("snapshot")
        except (ValueError, OSError):
            pass
    lang = ui.resolve_lang(request)
    t = app_strings(lang)
    return templates.TemplateResponse(request, "drive.html", {
        "country": cc, "city": city_slug, "city_name": c["name"], "district": district,
        "data_base": f"/citydata/{cc}/{city_slug}/{district}",
        "snapshot": snapshot,
        "cities": _available_cities(),
        "lang": lang, "t": t,
        # the HUD strings the client JS needs (warnings, route status, hover labels) — handed to the
        # canvas engine as window.CARSIM.i18n so it never has to know the language (msg 3080).
        "i18n_json": json.dumps(t, ensure_ascii=False),
        "user": auth.current_user(request),
    }, headers=HTML_HEADERS)


# ---- accounts: /me (user) + /admin (role=admin) — guests are redirected to /login ----------------

def _require_login(request: Request):
    u = auth.current_user(request)
    if u is None:
        return None, RedirectResponse(f"/login?next={request.url.path}", status_code=303)
    return u, None


@app.get("/me", response_class=HTMLResponse)
def me(request: Request):
    u, redirect = _require_login(request)
    if redirect:
        return redirect
    lang = ui.resolve_lang(request)
    return templates.TemplateResponse(request, "me.html", {
        "user": u, "trips": db.list_trips(u["id"], limit=50), "lang": lang, "t": app_strings(lang),
    }, headers=HTML_HEADERS)


@app.get("/me/export")
def me_export(request: Request):
    u, redirect = _require_login(request)
    if redirect:
        return redirect
    data = db.export_user(u["id"])
    return JSONResponse(data, headers={
        "Content-Disposition": 'attachment; filename="car-sim-my-data.json"',
        "Cache-Control": "no-store",
    })


@app.post("/me/delete")
def me_delete(request: Request):
    u, redirect = _require_login(request)
    if redirect:
        return redirect
    db.delete_user(u["id"])              # cascades trips/events
    auth.logout_user(request)
    return RedirectResponse("/", status_code=303)


def _require_admin(request: Request):
    u = auth.current_user(request)
    if u is None:
        return None, RedirectResponse(f"/login?next={request.url.path}", status_code=303)
    if u.get("role") != "admin":
        return None, JSONResponse({"error": "forbidden"}, status_code=403)
    return u, None


@app.get("/admin", response_class=HTMLResponse)
def admin(request: Request):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    q = request.query_params.get("q") or None
    users = db.list_users(q=q)
    return templates.TemplateResponse(request, "admin.html", {
        "user": u, "users": users, "q": q or "",
        "total": db.count_users(), "admin_emails": sorted(auth.ADMIN_EMAILS),
        "objects": db.list_objects(), "obj_cities": _available_cities(), "std_icons": STD_ICONS,
        "lang": ui.resolve_lang(request),
    }, headers=HTML_HEADERS)


@app.post("/admin/users/{uid}/role")
def admin_set_role(request: Request, uid: int, role: str = Form(...)):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    if role not in ("user", "admin"):
        raise HTTPException(status_code=400, detail="bad role")
    target = db.get_user(uid)
    if target and target["email"].lower() in auth.ADMIN_EMAILS and role != "admin":
        raise HTTPException(status_code=400, detail="cannot demote a configured admin email")
    db.set_role(uid, role)
    return RedirectResponse("/admin", status_code=303)


@app.post("/admin/users/{uid}/disable")
def admin_disable(request: Request, uid: int, disabled: str = Form("1")):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    db.set_disabled(uid, disabled == "1")
    return RedirectResponse("/admin", status_code=303)


@app.post("/admin/users/{uid}/delete")
def admin_delete(request: Request, uid: int):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    if uid == u["id"]:
        raise HTTPException(status_code=400, detail="refusing to delete yourself")
    db.delete_user(uid)
    return RedirectResponse("/admin", status_code=303)


# ---- map objects (msg 2983 ph3): admin places named icons/landmarks; the client renders them on /drive ----

_ICON_MAX = 256 * 1024  # 256 KB cap on a custom icon


def _save_icon(file: UploadFile) -> str:
    """Validate + store an admin-uploaded custom icon, returning its served URL path. Format is sniffed
    from the magic bytes (the client-sent content-type/filename is NOT trusted); the stored name is random."""
    data = file.file.read(_ICON_MAX + 1)
    if not data:
        raise HTTPException(status_code=400, detail="empty icon file")
    if len(data) > _ICON_MAX:
        raise HTTPException(status_code=400, detail="icon too large (max 256 KB)")
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        ext = ".png"
    elif data[:3] == b"\xff\xd8\xff":
        ext = ".jpg"
    elif data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        ext = ".webp"
    elif b"<svg" in data[:2048].lower():
        ext = ".svg"
    else:
        raise HTTPException(status_code=400, detail="unsupported icon format — use PNG, JPG, WebP or SVG")
    fname = f"obj_{secrets.token_hex(8)}{ext}"
    (UPLOADS / fname).write_bytes(data)
    return f"/uploads/{fname}"


@app.get("/api/objects")
def api_objects(city: str = DEFAULT_CITY_SLUG):
    """Public: the admin-placed objects for a city, in world coords the client renders directly."""
    if _city(city) is None:
        return JSONResponse([], headers={"Cache-Control": "no-cache"})
    out = [{"id": o["id"], "name": o["name"], "description": o["description"],
            "kind": o["kind"] or None, "icon": o["icon"] or None, "x": o["x"], "y": o["y"]}
           for o in db.list_objects(city)]
    return JSONResponse(out, headers={"Cache-Control": "no-cache"})


@app.post("/admin/objects")
def admin_create_object(request: Request, city: str = Form(...), name: str = Form(...),
                        description: str = Form(""), kind: str = Form(""),
                        lat: float = Form(...), lon: float = Form(...),
                        icon: UploadFile | None = File(None)):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    if _city(city) is None:
        raise HTTPException(status_code=400, detail="unknown city")
    name = name.strip()
    if not name:
        raise HTTPException(status_code=400, detail="name required")
    proj = _city_proj(city)
    if not proj:
        raise HTTPException(status_code=400, detail="city not baked")
    # a custom uploaded icon wins; otherwise a standard-library kind is required
    has_upload = icon is not None and bool(getattr(icon, "filename", ""))
    icon_path, kind_val = None, None
    if has_upload:
        icon_path = _save_icon(icon)
    elif kind in STD_ICONS:
        kind_val = kind
    else:
        raise HTTPException(status_code=400, detail="pick a standard icon or upload a custom one")
    x, y = _project(proj, lat, lon)
    db.create_object(city=city, name=name, description=(description.strip() or None),
                     kind=kind_val, icon=icon_path, lat=lat, lon=lon, x=x, y=y,
                     created_by=u["id"])
    return RedirectResponse("/admin#objects", status_code=303)


@app.post("/admin/objects/{oid}/delete")
def admin_delete_object(request: Request, oid: int):
    u, redirect = _require_admin(request)
    if redirect:
        return redirect
    o = db.get_object(oid)
    if o and o.get("icon"):                          # drop the uploaded file too (best-effort)
        fn = o["icon"].rsplit("/", 1)[-1]
        if fn.startswith("obj_"):
            (UPLOADS / fn).unlink(missing_ok=True)
    db.delete_object(oid)
    return RedirectResponse("/admin#objects", status_code=303)
